FROM rapidsai/rapidsai-core:0.18-cuda10.1-runtime-ubuntu18.04-py3.8
RUN apt-get update && conda activate rapids && conda install -c conda-forge mlxtend && conda install -c conda-forge python-graphviz
